book/urls.py
from django.urls import path
from book import views

app_name = 'book'
urlpatterns = [
    path('<str:book_id>/', views.Detail.as_view(), name='detail'),
    path('review/create/<str:book_id>', views.ReviewCreate.as_view(), name='review'),
    path('review/delete/<str:book_id>/review', views.ReviewDelete.as_view(), name='review_delete'),
    path('add-to-shelf', views.AddToShelf.as_view(), name='add_to_shelf'),
    path('remove-from-shelf/<str:book_id>', views.RemoveFromShelf.as_view(), name='remove_from_shelf')
]

learn/urls.py
from django.contrib import admin
from django.urls import path
from learn import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from home import urls as home_url
from library import urls as library_url
from book import urls as book_url
from author import urls as author_url
from user import urls as user_url
from user.views import CallbackView
#
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_url)),
    path('callback/', CallbackView.as_view(), name='callback'),
    path('library/', include(library_url)),
    path('book/', include(book_url)),
    path('author/', include(author_url)),
    path('user/', include(user_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from library import views

app_name = 'library'
urlpatterns = [
    path('', views.Library.as_view(), name='library'),
    path('search/', views.SearchBook.as_view(), name='search_book'),
    path('genre/<slug:slug>/', views.GenreDetail.as_view(), name='genre'),
]

user/urls.py
from django.urls import path
from learn import settings
from . import views

app_name = 'user'
urlpatterns = [
    path('logout/', views.Logout.as_view(), name='logout'),
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),
    path('profile/<int:user_id>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:user_id>/shelves/<int:shelf_id>', views.ShelfView.as_view(), name='shelves'),
    path('<str:user_id>/shelf/<str:shelf_id>/book/<str:book_id>/remove',
         views.ShelfRemoveBook.as_view(), name='book_remove'),
    path('review<str:review_id>/edit', views.EditReview.as_view(), name='edit_review'),
    # path('comment/', views.CommentPost.as_view(), name='comment')
]

library/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from book.models import *
from user.models import *
from django.views.generic import View
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, reverse
from .utils import load_books_isbn, store_books, search_book

isbns = ['0399590595', '1982110562', '0735219095', '0062963678', '0525536612', '0385543786', '1501190628',
         '1250265703', '0062200674', '1538731339', '0399181393', '0451494342', '1629996297', '0525535276',
         '0525656154']


class Library(View):
    def get(self, request):
        no_photo = 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png'
        # store_books()
        # books = Book.objects.filter(book_id='lkj')
        # for isbn in isbns:
        #     book = Book.objects.filter(book_id=isbn)
        #     print(book, 'yes')
        #     books |= book
        books = Book.objects.all().order_by('-average_rating').exclude(image=no_photo)
        valid_user = "False"
        all_users = list(CustomUser.objects.all())
        if not request.user.is_authenticated:
            timer = "yes"
        else:
            timer = "no"
        return render(request, 'library/library.html', {'books': books, 'valid_user': valid_user,
                                                        'timer': timer, 'error': False, 'all_users': all_users})

    def post(self, request):
        books = Book.objects.all()
        name = request.POST.get('name')
        password = request.POST.get('password')
        valid_user = "False"
        timer = "Not Exists"
        error = True
        all_users = list(CustomUser.objects.all())
        auth = authenticate(username=name, password=password)
        print(auth)
        if auth:
            login(request, auth)
            error = False
            valid_user = "True"
        return render(request, 'library/library.html', {'books': books, 'valid_user': valid_user,
                                                        'timer': timer, 'error': error, 'all_users': all_users})


class SearchBook(View):
    def get(self, request):
        text = request.GET.get('search')
        [books, t1] = search_book(text)
        return render(request, 'library/search_book.html', {'books': books, 't1': t1})


class GenreDetail(View):
    def get(self, request, slug):
        # slug = self.kwargs['slug']
        book = Genre.objects.get(slug=slug)
        return render(request, 'library/genre.html', {'book': book})

library/templates/library/genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author</title>
</head>
<body>

</body>
</html>

library/templates/library/library-header.html
<header class="library-header" style="position:fixed;z-index: 4">
    <div class="lib-container">
        <div class="lib-logo">
            <img src="/static/LOGO7.png" alt="LOGO" class="nav-logo">
            <span class="nav-logo-heading">WISE CLUB</span>
        </div>
        <nav class="nav-library">
        <ul class="nav-ul">
            <li class="search-box">
                <form action="{% url 'library:search_book' %}" method="get">
                    <input name="search" type="text" placeholder="Search your book here">
                    <button type="submit" style="background: transparent; border: none;cursor: pointer;outline: none;">
                        <i class="fas fa-search search-icon"></i>
                    </button>
                </form>
            </li>
            {% if request.user.is_authenticated == False %}
            <li class="lib-item lib-items lib-1"><a href="{% url 'user:sign-up' %}">Sign-up</a></li>
            <li class="lib-item lib-items lib-2"><a href="#" class="no loginPopup">Login</a></li>
            {% else %}
            <li class="lib-item lib-4"><a href="{% url 'user:profile' user_id=request.user.user_id %}" class="lib-profile"><img class="lib-profile-image" src={{request.user.image}} alt=""></a></li>
            <li class="lib-item lib-items lib-3"><a href="{% url 'user:logout' %}?next={{request.path}}" class="library-login">Logout</a></li>
            {% endif %}
            <!-- <li class="lib-item lib-4"><a></a></li> -->
        </ul>
        </nav>
    </div>
</header>

library/templates/library/library.html
{% extends 'home/base.html' %}
{% block body %}
<body style="padding:0px">
   {% include 'library/library-header.html' %}
<div class="model-back">
   <div class="model">
        <!-- <h4 class="popup-head">Be The Member Of Amazing Wise Club</h4> -->
        <h4 class="popup-head">Login To Wise Club</h4>
        <a href="#" class="no close-svg"><img src="/static/close.svg" alt="" class="close"></a>
        <form action="{% url 'library:library' %}" class="form" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input name="name" type="text" placeholder="Username" id="name" required class="form-input lib-login-username" autocomplete="off">
                <label for="name" class="label">Username</label>
            </div>
            <div class="form-group last-form-popup">
                <input name="password" type="password" placeholder="Password" id="password" required class="form-input" autocomplete="off">
                <label for="password" class="label">Password</label>
            </div>
            {% if error %}
            <div class="error-popup"><img src="/static/error_icon.png" alt="!"><span>Incorrect username or password</span></div>
            {%endif%}
            <div class="btn-box">
                <button class="btn-fire" id="btn5">Login &rarr;</button>
            </div>
        </form>
    </div>
</div>
<main class="u-padding-top-medium u-padding-bottom-medium home" style="padding-top: 180px">
    <div class="grid-center">
    <div class="grid">
        {% for book in books %}
        <div class="grid__item">
            <a href="{% url  'book:detail' book_id=book.book_id%}">
            <div class="card">
                <img class="card__image" src={{book.image}} alt="IMAGE">
                <div class="details">
                    <div class="card__name"><span class="span__name">{{book.title}}</span></div>
                    <div class="card__author"><span class="span__author">{%for main_author in book.author.all|slice:":1"%}
                        - {{main_author}}
                        {% endfor %}</span></div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
</main>

{% include 'user/login_base.html' %}
</body>
{% endblock %}

library/templates/library/search_book.html
{% extends 'home/base.html' %}
{% block body %}
<body style="padding:0px">
   {% include 'library/library-header.html' %}
<div class="model-back">
   <div class="model">
        <!-- <h4 class="popup-head">Be The Member Of Amazing Wise Club</h4> -->
        <h4 class="popup-head">Login To Wise Club</h4>
        <a href="#" class="no close-svg"><img src="/static/close.svg" alt="" class="close"></a>
        <form action="{% url 'library:library' %}" class="form" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input name="name" type="text" placeholder="Username" id="name" required class="form-input lib-login-username" autocomplete="off">
                <label for="name" class="label">Username</label>
            </div>
            <div class="form-group last-form-popup">
                <input name="password" type="password" placeholder="Password" id="password" required class="form-input" autocomplete="off">
                <label for="password" class="label">Password</label>
            </div>
            {% if error %}
            <div class="error-popup"><img src="/static/error_icon.png" alt="!"><span>Incorrect username or password</span></div>
            {%endif%}
            <div class="btn-box">
                <button class="btn-fire" id="btn5">Login &rarr;</button>
            </div>
        </form>
    </div>
</div>
<main class="u-padding-top-medium u-padding-bottom-medium home" style="padding-top: 180px">
    <div class="grid-center">
    <div class="grid">
        {% for book in books %}
        <div class="grid__item">
            <a href="{% url  'book:detail' book_id=book.id%}">
            <div class="card">
                <img class="card__image" src={{book.image_url}} alt="IMAGE">
                <div class="details">
                    <div class="card__name"><span class="span__name">{{book.title}}</span></div>
                    <div class="card__author"><span class="span__author">-{{book.author_name}}</span></div>
                </div>
            </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
</main>

{% include 'user/login_base.html' %}
<script>
    // window.addEventListener('load', threadCheck)
    // async function threadCheck(){
    //     while('{{t1.isAlive}}' != "False"){
    //     console.log(true);
    // }
    // }
</script>
</body>
{% endblock %}