author/urls.py
from django.urls import path
from author import views

app_name = 'author'
urlpatterns = [
    path('<slug:slug>/', views.AuthorDetail.as_view(), name='author'),
]

book/urls.py
from django.urls import path
from book import views

app_name = 'book'
urlpatterns = [
    path('<str:book_id>/', views.Detail.as_view(), name='detail'),
    path('review/create/<str:book_id>', views.ReviewCreate.as_view(), name='review'),
    path('review/delete/<str:book_id>/review', views.ReviewDelete.as_view(), name='review_delete'),
    path('add-to-shelf', views.AddToShelf.as_view(), name='add_to_shelf'),
    path('remove-from-shelf/<str:book_id>', views.RemoveFromShelf.as_view(), name='remove_from_shelf')
]

learn/urls.py
from django.contrib import admin
from django.urls import path
from learn import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from home import urls as home_url
from library import urls as library_url
from book import urls as book_url
from author import urls as author_url
from user import urls as user_url
from user.views import CallbackView
#
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_url)),
    path('callback/', CallbackView.as_view(), name='callback'),
    path('library/', include(library_url)),
    path('book/', include(book_url)),
    path('author/', include(author_url)),
    path('user/', include(user_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from learn import settings
from . import views

app_name = 'user'
urlpatterns = [
    path('logout/', views.Logout.as_view(), name='logout'),
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),
    path('profile/<int:user_id>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:user_id>/shelves/<int:shelf_id>', views.ShelfView.as_view(), name='shelves'),
    path('<str:user_id>/shelf/<str:shelf_id>/book/<str:book_id>/remove',
         views.ShelfRemoveBook.as_view(), name='book_remove'),
    path('review<str:review_id>/edit', views.EditReview.as_view(), name='edit_review'),
    # path('comment/', views.CommentPost.as_view(), name='comment')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from book.models import Book

rating_choices = (
    (0, 'no rating'),
    (1, 'did not like it'),
    (2, 'it was ok'),
    (3, 'liked it'),
    (4, 'really liked it'),
    (5, 'it was amazing')
)


class Status(models.Model):
    status_id = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    action_text = models.CharField(max_length=500)
    updated_at = models.CharField(max_length=100)
    body = models.TextField(null=True)
    image = models.URLField()

    def __str__(self):
        return self.action_text


class Shelf(models.Model):
    shelf_id = models.CharField(unique=True, max_length=200)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    books = models.ManyToManyField(Book, blank=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    review_id = models.CharField(unique=True, max_length=200)
    body = models.TextField()
    rating = models.PositiveIntegerField(choices=rating_choices, default=3)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    shelf = models.ForeignKey(Shelf, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.rating, self.body)


class CustomUser(AbstractUser):
    user_id = models.CharField(unique=True, max_length=200)
    name = models.CharField(max_length=500, default='')
    interests = models.CharField(max_length=700, null=True)
    fav_books = models.CharField(max_length=700, null=True)
    best_quote = models.CharField(max_length=720, null=True)
    friends_count = models.IntegerField(default=0)
    reviews_count = models.IntegerField(default=0)
    image = models.URLField(blank=True)

    request_token = models.CharField(max_length=720, default='')
    request_token_secret = models.CharField(max_length=720, default='')
    access_token = models.CharField(max_length=720, null=True)
    access_token_secret = models.CharField(max_length=720, null=True)

    def __str__(self):
        return self.username


class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

user/forms.py
from django import forms
from .models import CustomUser


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'pass'
    }))
    password2 = forms.CharField(max_length=30, widget=forms.PasswordInput(attrs={
        'class': 'pass'
    }))

    class Meta:
        model = CustomUser
        fields = ('username', 'name', 'email')

user/views.py
from django.shortcuts import render
from django.views.generic import View
from .forms import SignUpForm
from book.models import Book
from django.http import HttpResponse
from django.shortcuts import reverse
from django.shortcuts import redirect
from user.models import CustomUser, Review, Shelf
from django.contrib.auth import logout, login
from django.shortcuts import redirect
from django.contrib.auth.hashers import make_password
from .utils import load_user_id_data, get_user_data, get_shelf_data, edit_review
from .models import Status
from learn.utils import view_utils as main_utils
from rauth.service import OAuth1Service, OAuth1Session
import requests
from django.http import HttpResponseRedirect


CONSUMER_KEY = 'ePqGSFb6Pt7Xll8EnFzQJA'
CONSUMER_SECRET = 'Y7V0YdQpwW5908NGWna8GeAQWUEP6s4IK6fAQqb0JM'

goodreads = OAuth1Service(
    consumer_key=CONSUMER_KEY,
    consumer_secret=CONSUMER_SECRET,
    name='goodreads',
    request_token_url='https://www.goodreads.com/oauth/request_token',
    authorize_url='https://www.goodreads.com/oauth/authorize',
    access_token_url='https://www.goodreads.com/oauth/access_token',
    base_url='https://www.goodreads.com/'
)


class Profile(View):
    def get(self, request, user_id):
        # print(request.user.image)
        [statuses, user_shelves, friends] = get_user_data(request.user)
        user_quotes = [status for status in statuses if status.type == 'userquote']
        return render(request, 'user/profile.html', {'statuses': statuses, 'user_shelves': user_shelves,
                                                     'user_quotes': user_quotes, 'friends': friends})


class ShelfView(View):
    def get(self, request, user_id, shelf_id):
        get_shelf_data(request.user)
        shelf = Shelf.objects.filter(shelf_id=shelf_id, user=request.user)[0]
        reviews = Review.objects.filter(shelf=shelf, user=request.user)
        shelves = Shelf.objects.filter(user=request.user).exclude(name='delete')
        return render(request, 'user/shelves.html', {'shelves': shelves, 'reviews': reviews})


class ShelfRemoveBook(View):
    def get(self, request, book_id, shelf_id, user_id):
        return main_utils.delete_review_view(book_id, 'shelf', user_id, request.user)


class Logout(View):
    def get(self, request):
        logout(request)
        # print(self.request.GET.get('next'))
        return redirect('library:library')


class SignUp(View):
    def get(self, request):
        all_users = []
        for user in CustomUser.objects.all():
            all_users.append(str(user.username))
        return render(request, 'user/sign-up.html', {'all_users': all_users})

    def post(self, request):
        username = request.POST.get('username')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        print(username)
        l = []
        for i in CustomUser.objects.all():
            l.append(i.username)
        if username in l:
            return render(request, 'user/sign-up.html', {'error': 'Username already exists'})
        elif pass1 != pass2:
            return render(request, 'user/sign-up.html', {'error': 'Password and Password Confirm is not Matching'})
        else:
            password = make_password(pass1)
            request_token, request_token_secret = goodreads.get_request_token(header_auth=True)
            # user = CustomUser.objects.filter(username=username)
            user = CustomUser.objects.create(username=username, password=password, request_token=request_token,
                                             request_token_secret=request_token_secret)
            authorize_url = goodreads.get_authorize_url(request_token)
            return HttpResponseRedirect(authorize_url)


class CallbackView(View):
    def get(self, request):
        user = CustomUser.objects.none()
        try:
            print('in callback')
            print(request.GET)
            request_token = request.GET.get('oauth_token')
            user = CustomUser.objects.get(request_token=request_token)
            if str(request.GET.get('authorize')) == '0':
                user.delete()
                return redirect('library:library')
            session = goodreads.get_auth_session(request_token, user.request_token_secret)
            user.access_token = session.access_token
            user.access_token_secret = session.access_token_secret
            user.save()
            print('now getting user id')
            load_user_id_data(session, user)
            login(request, user)
            return redirect('library:library')
        except Exception as e:
            print(e)
            user.delete()
            return HttpResponse('Some error occured while getting access token')


class EditReview(View):
    def get(self, request, review_id):
        review = Review.objects.get(review_id=review_id)
        print(review.body)
        text = review.body.replace("<br />",  '\n')
        text = text.strip()
        shelves = Shelf.objects.filter(user=request.user).exclude(name='delete')
        return render(request, 'user/review.html', {'review': review, 'text': text, 'shelves': shelves})

    def post(self, request, review_id):
        review = Review.objects.get(review_id=review_id)
        text = request.POST.get('review')
        rating = request.POST.get('rating')
        shelf_name = request.POST.get('shelf')
        shelf = Shelf.objects.get(name=shelf_name, user=request.user)
        book = review.book
        response = edit_review(review_id, text, rating, shelf_name, request.user)
        print(response.text)
        if response.status_code == 200:
            review.body = text
            review.rating = rating
            review.shelf = shelf
            review.save()
            # data = {'book_id': book.book_id, 'shelf': shelf.shelf_id}
            # r1 = s.get(dhost)
            # csrf_token = r1.cookies['csrftoken']
            # response2 = requests.post('http://127.0.0.1:8000'+ reverse('book:add_to_shelf'), data=data)
            # print(response2)
            return redirect(reverse('user:shelves', kwargs={'user_id': request.user.user_id,
                                                            'shelf_id': shelf.shelf_id}))
        return HttpResponse('learn ' + str(response.status_code))

user/templates/user/login_base.html
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
<script src="/static/js/library.js"></script>
<script>

    document.querySelector('.lib-login-username').addEventListener('input', checkUsernames);

    function checkUsernames(event){
        let list_user = "{{all_users|safe}}";
        let val = event.target.value.toString();
        if(list_user.includes(val)&&val!=""){
            $('.lib-login-username').css({'border-bottom': '5px solid #00FF00'});
        }
        else{
                $('.lib-login-username').css({'border-bottom': '5px solid red'});
            }

    }

    var valid_user = '{{valid_user}}';
    console.log(valid_user);
    var timer = '{{timer}}';
    console.log(timer);
    if(timer == "yes"){
        setTimeout(showPopup, 4000);
    }
    function showPopup(){
    $('.model-back').css({'visibility': 'visible'});
    }
    if(valid_user == "True"){
        $('.model-back').css({'visibility': 'hidden'});
    }
    else if(timer == "Not Exists"){
        $('.model-back').css({'visibility': 'visible'});
    }
    $('a.loginPopup').on('click', function(e){$('.model-back').css({'visibility': 'visible'})
    $('.error-popup').css({'display': 'none'});
});
    $('a.close-svg').on('click', function(e){
        $('.model-back').css({'visibility': 'hidden'});
});
</script>

user/templates/user/profile.html
{% extends 'home/base.html' %}
{% block body %}
<body style="padding:0px">
   {% include 'library/library-header.html' %}
<main class="u-padding-top-medium u-padding-bottom-medium home" style="padding-top: 140px">
   <div class="profile-main-box">
    <div class="profile-primary-box">
       <div class="profile-detail-box">
         <div class="profile-user-image"><img src={{request.user.image}} alt=""></div>
         <div class="profile-user-detail">
            <span class="user-label">Name </span><span class="user-info">{{request.user.name}}</span>
            <br><br><br>
            {% if request.user.interests %}
            <span class="user-label">Interests </span><span class="user-info">{{request.user.interests|safe}}</span>
            {% endif %}
            <br><br><br>
            {% if request.user.fav_books %}
            <span class="user-label">Favourite Books </span><span class="user-info">{{request.user.fav_books}}</span>
            {% endif %}
         </div>
      </div>
    <div class="profile-quote-box">
      {% if request.user.best_quote %}
      <span class="quote-head"><a href="#" style="text-decoration: none;">{{request.user.name}}</a>'s Best Quote<span>
      <span class="user-quote"><q>{{request.user.best_quote|safe}}</q></span>
      {% endif %}
    </div>
    </div>
    <div class="profile-secondary-box">
       <div class="profile-flex-item updates">
         {% for status in statuses %}
         {% if status.body %}
         <div class="status-box">
            <div class="status-action-box"><a href="#">{{request.user.name}}</a> {{status.action_text|safe}}</div>
            <div class="status-container">
               <div class="status-image-box"><img src={{status.image}} alt=""></div>
               <div class="status-body-box"><q>{{status.body|safe}}</q></div>
            </div>
            <div class="status-updated-at">{{status.updated_at|safe}}</div>
         </div>
         {% else %}
         <div class="status-box">
            <!-- <div class="status-action-box">{{request.user.name}} {{status.action_text|safe}}</div> -->
            <div class="status-container">
               <div class="status-image-box"><img src={{status.image}} alt=""></div>
               <div class="status-body-box"><q><a href="#">{{request.user.name}}</a> {{status.action_text|safe}}</q></div>
            </div>
            <div class="status-updated-at">{{status.updated_at|safe}}</div>
         </div>
         {% endif %}
         {% endfor %}
       </div>
       <div class="profile-flex-item user-data">
          <div class="shelves">
             {% if user_shelves %}
               <span><a href="#" style="text-decoration: none;">{{request.user.name}}</a>'s book shelves</span>
             {% endif %}
            {% for shelf in user_shelves %}
            <li class="shelves-item"><a class="shelves-link" href="{% url 'user:shelves' user_id=request.user.user_id shelf_id=shelf.shelf_id %}">{{shelf.name}}</a>({{shelf.books.all.count}})</li>
            {% endfor %}
         </div>
         <div class="friends">
            {% if friends %}
               <span><a href="#" style="text-decoration: none;">{{request.user.name}}</a>'s friends</span>
            {% endif %}
               {% for friend in friends %}
               <div class="friend">
                  <div class="friend-image"><img src={{friend.image}} alt=""></div>
                  <div class="friend-info">
                     <div class="friend-name">{{friend.name}}</div>
                     <div class="friend-count">{{friend.friends_count}} frien{{friend.friends_count|pluralize:"d,ds"}}  |  {{friend.reviews_count}} revie{{friend.reviews_count|pluralize:"w,ws"}}</div>
                     <div class="friend-count"></div>
                  </div>
               </div>
               {% endfor %}
         </div>
         <div class="quotes">
               {% if user_quotes %}
                 <span><a href="#" style="text-decoration: none;">{{request.user.name}}</a>'s Quotes</span>
               {% endif %}
              {% for quote in user_quotes %}
              <li class="quote"><q>{{quote.body|safe}}</q></li>
              {% endfor %}
         </div>
       </div>
    </div>
       </div>
   </div>
</main>         
</body>
{% endblock %}

user/templates/user/review.html
{% extends 'home/base.html' %}
{% block body %}
<body style="padding:0px">
   {% include 'library/library-header.html' %}
    <main class="u-padding-top-medium u-padding-bottom-medium home" style="padding: 140px 20px">
        <div class="comment-box" style="position: relative">
                <form action="{% url 'user:edit_review' review_id=review.review_id%}" method="POST" class="comment-form">
                    {% csrf_token %}
                    <h3 class="comment-box-heading">Edit Review</h3>
                    <h4 class="rating-head">My Rating</h4>
                    <div class="rating">
                        <input type="radio" name="rating" id="star5" value="5"><label for="star5" class="star-label">
                        </label>
                        <input type="radio" name="rating" id="star4" value="4"><label for="star4" class="star-label">
                        </label>
                        <input type="radio" name="rating" id="star3" value="3"><label for="star3" class="star-label">
                        </label>
                        <input type="radio" name="rating" id="star2" value="2"><label for="star2" class="star-label">
                        </label>
                        <input type="radio" name="rating" id="star1" value="1"><label for="star1" class="star-label">
                        </label>
                        <input type="radio" class="input0" name="rating" id="star0" value="0" checked><label for="star0" class="star-label label0">
                        </label>
                    </div>
                    <textarea name="review" placeholder="Enter your review" class="review-input">
                       {{text}}
                    </textarea>
                    <div class="shelf-review-box">
                            <h4>Shelf Name</h4>
                        <select name="shelf" required class="editSelectShelf">
                            <option value="" selected disabled hidden>Choose shelf</option>
                            {% for shelf in shelves %}
                            {% if review.shelf == shelf %}
                            <option value={{shelf.name}} selected>{{shelf.name}}</option>
                            {% else %}
                            <option value={{shelf.name}}>{{shelf.name}}</option>
                            {% endif %}
                            {% endfor %}
<!--                            <option>Add new shelf</option>-->
                        </select>
                    </div>
                    <button class="btn-comment" type="submit">POST</button>
                </form>
            </div>
    </main>
<script>
    var rating = '{{review.rating}}';
    var inputId = "star" + rating;
    console.log(inputId);
    var inp = document.getElementById(inputId);
    window.addEventListener('load', function(e){
        inp.checked = true;
        console.log(inp.checked);
    })
    $('.review-input').on('focus', function(e){
        $('.review-input')[0].style.height = "200px"
    })
    $('.review-input').on('focusout', function(e){
        $('.review-input')[0].style.height = "100px"
    })
    $('.comment-form').on('submit', funAddToShelf);
    function funAddToShelf(e){
        // e.preventDefault()
        $.ajax({
            type: "POST",
            url: "{% url 'book:add_to_shelf'%}",
            data: {
                "book_id": '{{review.book.book_id}}',
                "shelf": $('.editSelectShelf').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success:function(output){
                console.log('okks')
                alert(output);
            }
        });
    }
</script>
</body>
{% endblock %}

user/templates/user/shelves.html
{% extends 'home/base.html' %}
{% block body %}
<body style="padding:0px">
   {% include 'library/library-header.html' %}
<main class="u-padding-top-medium u-padding-bottom-medium home" style="padding-top: 140px">
   <div class="shelves-main-box">
      <div class="shelves-list">
         <h3 class="shelves-list-head">My Bookshelves</h3>
         {% for shelf in shelves %}
         <div class="shelf-item"><a href={% url 'user:shelves' user_id=request.user.user_id shelf_id=shelf.shelf_id %} class="shelf-link">{{shelf.name}}</a>({{shelf.books.all.count}})</div>
         {% endfor %}
      </div>
      <div class="shelf-info">
         <div class="single-book">
               <div class="book-item head" style="width:113.33px;text-align: left;padding: 20px 23px;">Cover</div>
               <div class="book-item book-title head">Title</div>
               <div class="book-item book-authors head">Author</div>
               <div class="book-item average-rating head">Average Rating</div>
               <div class="book-item my-review-rating head">Rating</div>
               <div class="book-item shelf head">Shelf</div>
               <div class="book-item body head">Review</div>
         </div>
         <table>
         {% for review in reviews %}
         <tr class="single-book">
            <td><a href="{% url 'book:detail' book_id=review.book.book_id %}"><img class="book-item book-image" src={{review.book.image}} alt=""></a></td>
            <td><div class="book-item book-title"><a href="{% url 'book:detail' book_id=review.book.book_id %}" class="book-link">{{review.book.title}}</a></div></td>
            <td><div class="book-item book-authors">
               {% for author in review.book.author.all %}
               <a href="{% url 'author:author' slug=author.slug %}" class="book-link">{{author.name}}</a>
               {% endfor %}
            </div></td>
            <td><div class="book-item average-rating">{{review.book.average_rating}}</div></td>
            <td><div class="book-item my-review-rating">
                {% if review.rating != 0 %}
                  {% for i in '12345' %}
                  {% if i == review.rating|slugify %}
                  <span class="noOfStar"></span>
                  {% else %}
                  <span></span>
                  {% endif %}
                  {% endfor %}
                {% else %}
                <span class="noOfStar" style="visibility:hidden"></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                {% endif %}
            </div></td>
            <td><div class="book-item shelf">{{review.shelf.name}}</div></td>
            <td><div class="book-item body">{{review.body|safe}}</div></td>
            <td>
               <div class="book-item change-icon">
                     <a href="{% url 'user:edit_review' review_id=review.review_id %}" class="editReview">
                        <i class="fas fa-edit edit-review-shelf"></i>
                     </a>
                     <a class="remBookShelf" href="{% url 'user:book_remove' user_id=request.user.user_id shelf_id=review.shelf.shelf_id book_id=review.book.book_id %}">
                        <i class="fas fa-times-circle delete-review-shelf"></i>
                     </a>
               </div>
            </td>
         </tr>
         {% endfor %}
         </table>
      </div>
   </div>
</main>
<script>
   $('.remBookShelf').on('click', funRemoveBookShelf);
   function funRemoveBookShelf(e){
         if(!confirm('This will remove this book from your shelf do you wants to continue!'))
         {
            e.preventDefault();
         }
      }
</script>
</body>
{% endblock %}

user/templates/user/sign-up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/home.css">
    <!-- <link rel="stylesheet" href="/static/css/card.css"> -->
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sacramento&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cute+Font&display=swap" rel="stylesheet">
    <title>Sign-up</title>
</head>
<body style="padding: 0;height: 100%;position: relative;">
    <div class="sign-up-video-box">
        <video class="bg-video-sign-up" autoplay muted loop>
            <source src="/static/globe.mp4">
                VIDEO NOT SUPPORTED
        </video>
    </div>
    <div class="sign-up-page-box">
        <img class="sign-up-image" src="/static/LOGO7.png" alt="">
        <div class="sign-up-box">
            <h1 class="sign-up-heading">
                Sign-up
            </h1>
            <form action="{% url 'user:sign-up' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input name="username" type="text" placeholder="Username" id="username" required class="form-input sign-username" autocomplete="off">
                    <label for="username" class="label">Username</label>
                </div>
<!--                <div class="form-group">-->
<!--                    <input name="name" type="text" placeholder="Name" id="name" required class="form-input">-->
<!--                    <label for="name" class="label">Name</label>-->
<!--                </div>-->
<!--                <div class="form-group">-->
<!--                    <input name="email" type="email" placeholder="Email" id="email" required class="form-input" >-->
<!--                    <label for="email" class="label">Email</label>-->
<!--                </div>-->
                <div class="form-group">
                    <input name="password1" type="password" placeholder="Password" id="password1" required class="form-input sign-password" autocomplete="off">
                    <label for="password1" class="label">Password</label>
                </div>
                <div class="form-group">
                    <input name="password2" type="password" placeholder="Password Confirm" id="password2" required class="form-input sign-password-confirm" autocomplete="off">
                    <label for="password2" class="label">Password Confirm</label>
                </div>
                <button type="submit" class="btn-fire">Submit</button>
            </form>
        </div>
        {% if error %}
        <div class="sign-up-error-box">
            <img src="/static/error_icon.png" alt="ERROR">
            <span>{{error}}</span>
        </div>
        {% endif %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script>

        // document.querySelector('.sign-username').addEventListener('input', checkUsernames);
        $('.sign-username').on('input', checkUsernames);
        $('.sign-password-confirm').on('input', checkPasswordConfirm);

        function checkUsernames(event){
            let list_user = {{all_users|safe}};
            let val = event.target.value.toString();
            console.log(list_user);
            if(!list_user.includes(val)&&val!=""){
                $('.sign-username').css({'border-bottom': '5px solid #00FF00'});
            }
            else{
                    $('.sign-username').css({'border-bottom': '5px solid red'});
                }

        }
        function checkPasswordConfirm(event){
            let list_user = {{all_users|safe}};
            let val = event.target.value.toString();
            let passVal = document.querySelector('.sign-password').value.toString();
            console.log(val,passVal);
            if(val == passVal&&val!=""){
                $('.sign-password-confirm').css({'border-bottom': '5px solid #00FF00'});
            }
            else{
                // console.log('not')
                    $('.sign-password-confirm').css({'border-bottom': '5px solid red'});
                }

        }

    </script>
</body>
</html>