author/urls.py
from django.urls import path
from author import views

app_name = 'author'
urlpatterns = [
    path('<slug:slug>/', views.AuthorDetail.as_view(), name='author'),
]

book/urls.py
from django.urls import path
from book import views

app_name = 'book'
urlpatterns = [
    path('<str:book_id>/', views.Detail.as_view(), name='detail'),
    path('review/create/<str:book_id>', views.ReviewCreate.as_view(), name='review'),
    path('review/delete/<str:book_id>/review', views.ReviewDelete.as_view(), name='review_delete'),
    path('add-to-shelf', views.AddToShelf.as_view(), name='add_to_shelf'),
    path('remove-from-shelf/<str:book_id>', views.RemoveFromShelf.as_view(), name='remove_from_shelf')
]

learn/urls.py
from django.contrib import admin
from django.urls import path
from learn import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from home import urls as home_url
from library import urls as library_url
from book import urls as book_url
from author import urls as author_url
from user import urls as user_url
from user.views import CallbackView
#
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home_url)),
    path('callback/', CallbackView.as_view(), name='callback'),
    path('library/', include(library_url)),
    path('book/', include(book_url)),
    path('author/', include(author_url)),
    path('user/', include(user_url)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from author.models import Author


types = (
    ('I', 'ISBN'),
    ('G', 'GID')
)


class Genre(models.Model):
    genre_id = models.CharField(unique=True, max_length=20, default='0')
    slug = models.SlugField(unique=True, max_length=40)
    name = models.CharField(max_length=25)
    info = models.TextField()

    def __str__(self):
        return self.name


class Book(models.Model):
    type = models.CharField(choices=types, max_length=1, default='I')
    book_id = models.CharField(unique=True, max_length=200, default='0')
    slug = models.SlugField(unique=True, max_length=400)
    title = models.CharField(max_length=250, null=True)
    average_rating = models.FloatField(default=0)
    author = models.ManyToManyField(Author)
    genre = models.ManyToManyField(Genre, blank=True)
    description = models.TextField(default='', null=True)
    similar_books = models.ManyToManyField('Book', blank=True)
    image = models.URLField()

    def __str__(self):
        return self.title

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from book.models import Book

rating_choices = (
    (0, 'no rating'),
    (1, 'did not like it'),
    (2, 'it was ok'),
    (3, 'liked it'),
    (4, 'really liked it'),
    (5, 'it was amazing')
)


class Status(models.Model):
    status_id = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    action_text = models.CharField(max_length=500)
    updated_at = models.CharField(max_length=100)
    body = models.TextField(null=True)
    image = models.URLField()

    def __str__(self):
        return self.action_text


class Shelf(models.Model):
    shelf_id = models.CharField(unique=True, max_length=200)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    books = models.ManyToManyField(Book, blank=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    review_id = models.CharField(unique=True, max_length=200)
    body = models.TextField()
    rating = models.PositiveIntegerField(choices=rating_choices, default=3)
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    shelf = models.ForeignKey(Shelf, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.rating, self.body)


class CustomUser(AbstractUser):
    user_id = models.CharField(unique=True, max_length=200)
    name = models.CharField(max_length=500, default='')
    interests = models.CharField(max_length=700, null=True)
    fav_books = models.CharField(max_length=700, null=True)
    best_quote = models.CharField(max_length=720, null=True)
    friends_count = models.IntegerField(default=0)
    reviews_count = models.IntegerField(default=0)
    image = models.URLField(blank=True)

    request_token = models.CharField(max_length=720, default='')
    request_token_secret = models.CharField(max_length=720, default='')
    access_token = models.CharField(max_length=720, null=True)
    access_token_secret = models.CharField(max_length=720, null=True)

    def __str__(self):
        return self.username


class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

book/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from book.models import *
from django.views.generic import View
from user.models import CustomUser, Comment, Review
from django.contrib.auth.hashers import make_password
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login, authenticate
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import redirect, reverse
from django.template.defaultfilters import linebreaks
from .utils import book_review_widget, post_review, get_review_id, delete_review, add_to_shelf
from user.models import Shelf
from learn.utils import view_utils as main_utils


class Detail(View):
    def get(self, request, book_id):
        try:
            valid_user = "False"
            book = Book.objects.get(book_id=book_id)
            reviews = book_review_widget(book)
            all_users = []
            # reviews = ''
            review = Review.objects.filter(book=book, user=request.user)
            if review:
                review = review[0]
            for user in CustomUser.objects.all():
                all_users.append(str(user.username))
            timer = "no"
            user = None
            shelves = Shelf.objects.filter(user=request.user).exclude(name='delete')
            book_shelf = book.shelf_set.all()
            if not book_shelf:
                book_shelf = 0
            else:
                book_shelf = 1
            if request.user.is_authenticated:
                user = CustomUser.objects.filter(username=request.user.username)[0]
            # comments = Comment.objects.filter(book=book)
            comments = None
            similar_books = book.similar_books.all()
            return render(request, 'book/detail.html', {'comments': comments, 'book': book, 'valid_user': valid_user,
                                                        'timer': timer, 'error': False, 'all_users': all_users,
                                                        'user': user, 'similar_books': similar_books,
                                                        'reviews': reviews, 'shelves': shelves,
                                                        'review': review, 'book_shelf': book_shelf})
        except Book.DoesNotExist:
            raise Http404

    def post(self, request, book_id):
        try:
            book = Book.objects.get(book_id=book_id)
            valid_user = "False"
            error = True
            timer = "Not Exists"
            all_users = []
            reviews = book_review_widget(book)
            review = Review.objects.filter(book=book, user=request.user)
            # reviews = ''
            comments = Comment.objects.filter(book=book)
            user = None
            shelves = Shelf.objects.all()
            for user in CustomUser.objects.all():
                all_users.append(str(user.username))
            if request.user.is_authenticated:
                valid_user = "True"
                error = False
                # print('yes')
                text = request.POST.get('text')
                user = CustomUser.objects.filter(username=request.user.username)[0]
                Comment.objects.create(text=text, user=user, book=book)
                return redirect(reverse('detail', kwargs={'book_id': book.book_id}))
            else:
                name = request.POST.get('name', None)
                if not name:
                    print('jlksfd')
                    return render(request, 'home/detail.html',
                                  {'comments': comments, 'book': book, 'valid_user': valid_user,
                                   'timer': timer, 'error': False, 'all_users': all_users})
                password = request.POST.get('password')
                auth = authenticate(username=name, password=password)
                error = True
                if auth:
                    login(request, auth)
                    error = False
                    user = CustomUser.objects.filter(username=request.user.username)[0]
                    valid_user = "True"
                # print('no')
        except Book.DoesNotExist:
            raise Http404
        return render(request, 'book/detail.html',
                      {'comments': comments, 'book': book, 'valid_user': valid_user,
                       'timer': timer, 'error': error, 'all_users': all_users,
                       'user': user, 'reviews': reviews, 'shelves': shelves, 'review': review})


class ReviewCreate(View):
    def post(self, request, book_id):
        review = request.POST.get('review')
        shelf_name = request.POST.get('shelf')
        shelf = Shelf.objects.get(name=shelf_name, user=request.user)
        rating = request.POST.get('rating', 0)
        print(book_id)
        book = Book.objects.get(book_id=book_id)
        response = post_review(review, shelf_name, book.book_id, rating, request.user)
        if response.status_code == 201:
            review_id = get_review_id(response)
            a = Review.objects.create(review_id=review_id, body=review, rating=rating,
                                      user=request.user, book=book, shelf=shelf)
            shelf.books.add(book)
            print(a.review_id)
            return redirect(reverse('book:detail', kwargs={'book_id': book.book_id}))
        return HttpResponse('learn')


class ReviewDelete(View):
    def get(self, request, book_id):
        return main_utils.delete_review_view(book_id, 'book')


class AddToShelf(View):
    def post(self, request):
        print('hiii')
        shelf_name = request.POST.get('shelf')
        book_id = request.POST.get('book_id')
        shelf = Shelf.objects.get(name=shelf_name, user=request.user)

        response = add_to_shelf(shelf_name, book_id, request.user)
        print(response)
        book = Book.objects.get(book_id=book_id)
        review = Review.objects.filter(book=book, user=request.user)
        if response.status_code == 201:
            if book.shelf_set.all():
                book.shelf_set.clear()
            shelf.books.add(book)
            if review:
                review = review[0]
                review.shelf = shelf
                review.save()
            return HttpResponse(book.title + ' is added to your shelf')
        return HttpResponse('learn')


class RemoveFromShelf(View):
    def get(self, request, book_id):
        return main_utils.delete_review_view(book_id, 'book', request.user.user_id, request.user)

book/templates/book/detail.html
{% extends 'home/base.html' %}
{% block body %}


<body class="book-detail">
{% include 'library/library-header.html' %}
<div class="model-back">
    <div class="model">
        <!-- <img src="/static/LOGO8.png" alt="" class="popup-img"> -->
        <!-- <h4 class="popup-head">Be The Member Of Amazing Wise Club</h4> -->
        <h4 class="popup-head">Login To Wise Club</h4>
        <a href="#" class="no close-svg"><img src="/static/close.svg" alt="" class="close"></a>
        <form action="{% url 'book:detail' book_id=book.book_id%}" class="form" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input name="name" type="text" placeholder="Username" id="name" required class="form-input lib-login-username" autocomplete="off">
                <label for="name" class="label">Username</label>
            </div>
            <div class="form-group last-form-popup">
                <input name="password" type="password" placeholder="Password" id="password" required class="form-input" autocomplete="off">
                <label for="password" class="label">Password</label>
            </div>
            {% if error %}
            <div class="error-popup"><img src="/static/error_icon.png" alt="!"><span>Incorrect username or password</span></div>
            {%endif%}
            <div class="btn-box">
                <button class="btn-fire" id="btn5">Login &rarr;</button>
            </div>
        </form>
    </div>
</div>
<main style="padding: 110px 15px;position: absolute;top: 0px;box-sizing: border-box">
    <div class="layout__detail">
        <div class="detail-card">
            <div class="information">
                <img class="layout__item" src={{ book.image }} alt="IMAGE">
                <div class="text-box">
                    <h3 class="text-box__heading--name"><span class="span__name">{{book.title}}</span></h3>
                    <h3 class="by">By</h3>
                    <h3 class="text-box__heading--author"><span class="span__author">
                        {% for author in book.author.all %}
                            <a href="{% url 'author:author' slug=author.slug %}" class="btn-rotate">{{author}}</a>&nbsp;
                        {% endfor %}</span></h3>
                    <div class="add-to-shelf">
                        <select name="shelf" class="select-add-to-shelf" id="oldValueRef">
                            <option value="" selected disabled hidden>Add To Shelf</option>
                            {% for shelf in shelves %}
                            {% if shelf in book.shelf_set.all %}
                            <option value={{shelf.name}} selected>{{shelf.name}}</option>
                            {% else %}
                            <option value={{shelf.name}}>{{shelf.name}}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <a href="{% url 'book:remove_from_shelf' book_id=book.book_id %}">
                            <i class="fas fa-times remove-book"></i>
                        </a>
                        <!-- <img class="drop-down" src="\static\drop-down.svg" alt=""> -->
                    </div>
                </div>
                <!-- <div style="clear: both"></div> -->
            </div>
            <div class="summary u-margin-top-medium">
                <h3>Summary</h3>
                <div class="text">
                    <span class="span__text">{{book.description|safe}}</span>
                </div>
            </div>
        {% if not review %}
        <div class="comment-box" style="position: relative">
            <form action="{% url 'book:review' book_id=book.book_id %}" method="POST" class="comment-form">
                {% csrf_token %}
                <h3 class="comment-box-heading">Write a review</h3>
                <h4 class="rating-head">My Rating</h4>
                <div class="rating">
                    <input type="radio" name="rating" id="star5" value="5"><label for="star5" class="star-label">
                    </label>
                    <input type="radio" name="rating" id="star4" value="4"><label for="star4" class="star-label">
                    </label>
                    <input type="radio" name="rating" id="star3" value="3"><label for="star3" class="star-label">
                    </label>
                    <input type="radio" name="rating" id="star2" value="2"><label for="star2" class="star-label">
                    </label>
                    <input type="radio" name="rating" id="star1" value="1"><label for="star1" class="star-label">
                    </label>
                    <input type="radio" class="input0" name="rating" id="star0" value="0" checked><label for="star0" class="star-label label0">
                    </label>
                </div>
                <textarea name="review" placeholder="Enter your review" class="review-input"></textarea>
                <div class="shelf-review-box">
                        <h4>Shelf Name</h4>
                    <select name="shelf" required>
                        <option value="" selected disabled hidden>Choose shelf</option>
                        {% for shelf in shelves %}
                        <option value={{shelf.name}}>{{shelf.name}}</option>
                        {% endfor %}
                        <option>Add new shelf</option>
                    </select>
                </div>
                <button class="btn-comment" type="submit">POST</button>
            </form>
        </div>
        {% else %}
        <h4 class="my-review-head">My Review</h4>
        <div class="previous-comment">
            <img src={{request.user.image}} alt="">
            <div class="previous-comment-text-box">
                <div class="my-review-rating">
                    {% for i in '12345' %}
                    {% if i == review.rating|slugify %}
                    <span class="noOfStar"></span>
                    {% else %}
                    <span></span>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="previous-comment-text">{{review.body|safe|linebreaks}}</div>
            </div>
            <a class="delete-review" href="{% url 'book:review_delete' book_id=book.book_id %}"><img src="\static\del.png" alt="delete"></a>
        </div>
        {% endif %}
            {% if similar_books %}
            <h4 class="detail-similar-books-heading">Similar Books</h4>
            {% endif %}
        <div class="flex_similar">
        {% for book in similar_books %}
            <a href="{% url  'book:detail' book_id=book.book_id%}">
            <div class="card">
                <img class="card__image" src={{book.image}} alt="IMAGE">
                <div class="details">
                    <div class="card__name"><span class="span__name">{{book.title}}</span></div>
                    <div class="card__author"><span class="span__author">{%for main_author in book.author.all|slice:":1"%}
                        - {{main_author}}
                        {% endfor %}</span></div>
                </div>
            </div>
            </a>
        {% endfor %}
        </div>
        <h3 class="comment-box-heading">Wise Community Reviews</h3>
        {{reviews|safe}}
        </div>
    </div>
</main>
{% include 'user/login_base.html' %}
<script>
    var oldValue;
    window.addEventListener('load', function(){
        oldValue = $('.select-add-to-shelf').val();
        // console.log('{{book_shelf|safe|length}}');
        if('{{book_shelf}}' == 0){
            console.log('{{book_shelf|safe}}');
            $('.remove-book').css({"opacity":0})
        }
    })
    $('.review-input').on('focus', function(e){
        $('.review-input')[0].style.height = "200px"
    })
    $('.review-input').on('focusout', function(e){
        $('.review-input')[0].style.height = "100px"
    })
    $('.select-add-to-shelf').on('change', funAddToShelf)
    $('.delete-review').on('click', funDeleteReview);
    $('.remove-book').on('click', funRemoveBook);
    function funDeleteReview(e){
        if(!confirm('This will delete the review and remove this book from your shelf do you wants to continue!'))
        {
            e.preventDefault();
        }
    }
    function funRemoveBook(e){
        if(!confirm('This will remove this book from your shelf do you wants to continue!'))
        {
            e.preventDefault();
        }
    }
    function funAddToShelf(){
        if(!confirm('Do you want to add this book to this shelf')){
            console.log(oldValue)
            $('.select-add-to-shelf').val(oldValue);
            return;
        }
        $.ajax({
            type: "POST",
            url: "{% url 'book:add_to_shelf'%}",
            data: {
                "book_id": '{{book.book_id}}',
                "shelf": $('.select-add-to-shelf').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success:function(output){
                oldValue =  $('.select-add-to-shelf').val();
                alert(output);
            }
        });
        $('.remove-book').css({"opacity":1})
    }
</script>
<style>
        #goodreads-widget{
            font-size: 20px;
        width: 100%;
        height: 1000px;
      }
      iframe{
    width: 100%;
    height: 1000px;
    background-color: #fff;
    }
    #goodreads-widget h1 {
    display: none;
  }
  #gr_footer {
    display: none;
  }
  #goodreads-widget .gr_branding{
    color: #382110;
    font-size: 20px;
    text-decoration: none;
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
    </style>
</body>
{% endblock %}